# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from srs_sdk.api.words_api import WordsApi


class TestWordsApi(unittest.TestCase):
    """WordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WordsApi()

    def tearDown(self) -> None:
        pass

    def test_create_word_words_post(self) -> None:
        """Test case for create_word_words_post

        Create Word
        """
        pass

    def test_delete_word_words_word_id_delete(self) -> None:
        """Test case for delete_word_words_word_id_delete

        Delete Word
        """
        pass

    def test_get_due_words_words_due_get(self) -> None:
        """Test case for get_due_words_words_due_get

        Get Due Words
        """
        pass

    def test_get_history_words_history_get(self) -> None:
        """Test case for get_history_words_history_get

        Get History
        """
        pass

    def test_get_word_hint_words_word_id_hint_get(self) -> None:
        """Test case for get_word_hint_words_word_id_hint_get

        Get Word Hint
        """
        pass

    def test_submit_review_words_word_id_review_post(self) -> None:
        """Test case for submit_review_words_word_id_review_post

        Submit Review
        """
        pass


if __name__ == '__main__':
    unittest.main()
